name: Deploy
on:
  push:
    branches:
      - staging
      - production
    pull_request:
      branches:
        - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn check:api
