name: e2e tests
on:
  push:
    branches:
      - test-ci
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
        with:
          repository: 'Entkenntnis/serlo-codecept'
      - run: echo "module.exports = {username:'',password:'',userPassword:'123456'}" > secrets.js
      - run: npm ci
      - run: |
        HEADLESS=true npm run codeceptjs --override '{"helpers":{"chrome":"arg": ["--headless", "--no-sandbox"]}}' --steps
