name: e2e tests
on:
  push:
    branches:
      - staging
      # testing
      - test-ci
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
        with:
          repository: 'Entkenntnis/serlo-codecept'
      - uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          check_interval: 10
      - run: echo "module.exports = {username:'',password:'',userPassword:'123456'}" > secrets.js
      - run: npm ci
      - run: npm run codeceptjs
